name: mealie
services:
- name: mealie
  github:
    branch: main
    deploy_on_push: true
    repo: leshicodes/mealie.jjambrose.info
  http_port: 9000
  dockerfile_path: Dockerfile # Changed to use Dockerfile
  instance_size_slug: basic-xxs
  instance_count: 1  # Explicitly set to 1 instance
  health_check:
    http_path: /
    port: 9000
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: ALLOW_SIGNUP
    value: "false"
  - key: PUID
    value: "1000"
  - key: PGID
    value: "1000" 
  - key: TZ
    value: "America/Chicago"
  - key: BASE_URL
    value: ${APP_URL}
  volumes:
  - name: mealie-data
    mount_path: /app/data
    size_gb: 5
