name: mealie
services:
- name: mealie
  github:
    branch: main
    deploy_on_push: true
    repo: leshicodes/mealie.jjambrose.info
  http_port: 9000
  dockerfile_path: Dockerfile # Changed to use Dockerfile
  instance_size_slug: basic-s
  envs:
  - key: ALLOW_SIGNUP
    value: "false"
  - key: PUID
    value: "1000"
  - key: PGID
    value: "1000" 
  - key: TZ
    value: "America/Chicago"
  - key: BASE_URL
    value: ${APP_URL}
  volumes:
  - name: mealie-data
    mount_path: /app/data
    size_gb: 10


# name: mealie
# services:
# - name: mealie
#   type: service  # Explicitly defining type
#   github:
#     branch: main
#     deploy_on_push: true
#     repo: leshicodes/mealie.jjambrose.info
#   dockerfile_path: Dockerfile
#   http_port: 9000
#   instance_size_slug: basic-s
#   envs:
#   - key: ALLOW_SIGNUP
#     value: "false"
#   - key: PUID
#     value: "1000"
#   - key: PGID
#     value: "1000" 
#   - key: TZ
#     value: "America/Chicago"
#   - key: BASE_URL
#     value: ${APP_URL}
#   volumes:
#   - name: mealie-data
#     mount_path: /app/data
#     size_gb: 10